### ISSUE TITLE
Expected BioJS package folder structure?

### ISSUE THREAD

**Issue by DevasenaInupakutika** [biojs/biojs#143]
Can we have a skeleton structure of the directory for BioJS package in its wiki similar to the one mentioned in BioJS 1.0 documentation as an example [here] (https://docs.google.com/document/d/1oS4M0EKAMre4IDERV61VVTDXJH9F-HGbHxKwNXqjWuo/edit)?

i.e. The default or basic structure of directory that we get after running this command `cd <your-project> && slush biojs`.

**Comment by greenify** [comment]
Good idea :)
Is [this](https://github.com/biojs/biojs/wiki/BioJS-package:-file-structure) comprehensive?

**Comment by DevasenaInupakutika** [comment]
Yes! Thank you :+1:
