### ISSUE TITLE
Tutorial page is not working 404 error

### ISSUE THREAD

**Issue by igoralves1** [biojs/biojs#147]
I am trying to better understand what can we do with bioJs. For that I've try to tutorial page. We have a error 404. Is there another link?

**Comment by greenify** [comment]
> e have a error 404.

Which link are trying? Where did you get it from?

Our education portal is here: http://edu.biojs.net/
The registry: http://biojs.io

**Comment by igoralves1** [comment]
Hi this is the url http://edu.biojs.net/categories/101_tutorial/index.html

**Comment by greenify** [comment]
> Hi this is the url http://edu.biojs.net/categories/101_tutorial/index.html

Try http://edu.biojs.net/series/101/10_intro.html

Where have we published the broken link?

**Comment by igoralves1** [comment]
3.2. How to create a package?
read our guide  
guide link.
