### ISSUE TITLE
Wrong ReadMe is displayed on biojs

### ISSUE THREAD

**Issue by LLTommy** [biojs/biojs#162]
Yes, this is weird - but that is the situation I am in. I just pushed a new small module to bio.js that you can find [here](http://www.biojs.io/d/ols-treeview). It all looks fine first, but it is not because it displays the readme from my other package which you can find [here](http://www.biojs.io/d/ols-graphview). So first I thought that I messed something up, but if you check the readme on [github](https://github.com/LLTommy/OLS-treeview) and [npm](https://www.npmjs.com/package/ols-treeview) for the treeview package it contains the readme that was intended to go with this package. So I don't know how bio.js gets its content but something is really wrong here, maybe the somewhat similar name gets it confused or whatever. But to display the wrong readme is not helpful for the potential users!

**Comment by LLTommy** [comment]
I think it is a copy paste error in my package.json after all. So I close this.

**Comment by jessica-jordan** [comment]
Sounds good, thanks for checking in!

**Comment by LLTommy** [comment]
Just to check back, it works now, so yes it was my faulty package.json after all. Sorry for all that, I just missed it yesterday after a looooong day at work :)

**Comment by jessica-jordan** [comment]
No worries, great to hear that you found the issue already :-)
