### ISSUE TITLE
Links broken in Read Me

### ISSUE THREAD

**Issue by lnchapin** [biojs/biojs#166]
The links in the the read me in section 4.4. Documentation are throwing a 403 error, this includes the tutorial and all of http://edu.biojs.net/

**Comment by leechuck** [comment]
There are also dead-ish links to biojs.io, which should probably point to biojs.net.

**Comment by yochannah** [comment]
Whoops, thanks for letting us know!

**Comment by yochannah** [comment]
I'm hopeful we fixed the broken links 👍
