### ISSUE TITLE
wrapper/integration guides to bioJS 2

### ISSUE THREAD

**Issue by timruffles** [biojs/biojs#86]
we should tell people how to make their component easy to integrate via the BioJS event object
- [ ] angularjs
- [ ] jquery
- [ ] vanilla
- [ ] polymer

**Comment by greenify** [comment]
Actually integrating BioJS components in Angular is straight forward - here is [an example](http://plnkr.co/edit/G0VghsuhWh1ZiSQuU8Ms?p=preview) with the MSA component.

@emepyc created [a WebComponent/Polymber example](http://bl.ocks.org/emepyc/5b018c2d42048090057b) of his TNT component.

For jQuery and VanillaJS on can directly edit the registry examples provided in JSBin/Codepen. 
(the only difference is that jQuery allows to shorten `document.getElementById(<id>)` to `$(#<id>)`).
